const { assert } = require('chai');
const relationStorage = require('../storage/mongo/relation'); 
const { struct } = require('pb-util');
const { v4 } = require("uuid");


describe('Relation testing', function () {
    this.timeout('5000s')
    let types = [
        "Many2Dynamic",
        "Many2Many",
        "Recursive",
        "Many2One",
    ]

    let ids = []

    it('Create relation', async () => {
        for(let type of types) {
            let id = v4()
            let payload = {
                project_id: "ecb08c73-3b52-42e9-970b-56be9b7c4e81",
                id: id,
                "table_from": "setting.timezones",
                "auto_filters": [],
                "action_relations": [],
                "attributes": {},
                "table_to": "setting.languages",
                "type": type,
                "default_limit": "",
                "multiple_insert": false,
                "filtersList": [
                    {
                    "attributes": {
                        "creatable": false,
                        "defaultValue": "",
                        "disabled": false,
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "6942f498-4097-44f0-837a-8a263420c7b2",
                        "guid": "06d51fc0-6084-4e4e-bf95-b99a0995c8d4",
                        "label": "name",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "placeholder": "",
                        "showTooltip": false,
                        "show_label": true
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "6942f498-4097-44f0-837a-8a263420c7b2",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "name",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": true,
                    "slug": "name",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "auto_filters": [],
                        "autofill": [],
                        "cascading_tree_field_slug": "",
                        "cascading_tree_table_slug": "",
                        "cascadings": [],
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                        "guid": "d2c0eac9-918f-4c7e-a3f6-dbea775a36b9",
                        "label": "FROM category TO connections",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "function_path": "",
                        "is_user_id_default": false,
                        "object_id_from_jwt": false,
                        "view_fields": []
                    },
                    "id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                    "label": "label",
                    "relation_id": "027cbe50-0f9a-4b2b-9433-69025dd198e1",
                    "required": false,
                    "slug": "connections_id",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "table_slug": "connections",
                    "type": "LOOKUP",
                    "view_fields": []
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                        "guid": "dd68e6a2-7404-4dbb-9652-e1a082277e22",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                        "guid": "05f30bc3-22cd-4b84-a6c8-4bc12a1db11c",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                        "guid": "eb2596f7-d43b-4fdd-9b17-0f654741dd5f",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                        "guid": "17d45ecf-a3eb-44fe-b8ea-660a6bd8fa3b",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                        "guid": "e2cc4d9b-1aec-4a41-93c3-4f5953a41df1",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                        "guid": "82e6cdb3-25c4-4ba8-ba6e-c1ff7cbf1e49",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                        "guid": "78ee1026-61de-40f5-9534-cdef3bc6848d",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                        "guid": "2a45c7cf-6729-42cb-8dbc-48af9bb3fa7c",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a0d30309-65f4-453a-8281-b35faccfda13",
                        "guid": "4a02e413-3b55-40a2-8adf-7bec0fe0b8b9",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a0d30309-65f4-453a-8281-b35faccfda13",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                        "guid": "d61fd658-ae56-435d-a2a9-27b0a4281408",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    }
                ],
                "columnsList": [
                    {
                    "attributes": {
                        "creatable": false,
                        "defaultValue": "",
                        "disabled": false,
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "6942f498-4097-44f0-837a-8a263420c7b2",
                        "guid": "06d51fc0-6084-4e4e-bf95-b99a0995c8d4",
                        "label": "name",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "placeholder": "",
                        "showTooltip": false,
                        "show_label": true
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "6942f498-4097-44f0-837a-8a263420c7b2",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "name",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": true,
                    "slug": "name",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "auto_filters": [],
                        "autofill": [],
                        "cascading_tree_field_slug": "",
                        "cascading_tree_table_slug": "",
                        "cascadings": [],
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                        "guid": "d2c0eac9-918f-4c7e-a3f6-dbea775a36b9",
                        "label": "FROM category TO connections",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "function_path": "",
                        "is_user_id_default": false,
                        "object_id_from_jwt": false,
                        "view_fields": []
                    },
                    "id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                    "label": "label",
                    "relation_id": "027cbe50-0f9a-4b2b-9433-69025dd198e1",
                    "required": false,
                    "slug": "connections_id",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "table_slug": "connections",
                    "type": "LOOKUP",
                    "view_fields": []
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                        "guid": "dd68e6a2-7404-4dbb-9652-e1a082277e22",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                        "guid": "05f30bc3-22cd-4b84-a6c8-4bc12a1db11c",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                        "guid": "eb2596f7-d43b-4fdd-9b17-0f654741dd5f",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                        "guid": "17d45ecf-a3eb-44fe-b8ea-660a6bd8fa3b",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                        "guid": "e2cc4d9b-1aec-4a41-93c3-4f5953a41df1",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                        "guid": "82e6cdb3-25c4-4ba8-ba6e-c1ff7cbf1e49",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                        "guid": "78ee1026-61de-40f5-9534-cdef3bc6848d",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                        "guid": "2a45c7cf-6729-42cb-8dbc-48af9bb3fa7c",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a0d30309-65f4-453a-8281-b35faccfda13",
                        "guid": "4a02e413-3b55-40a2-8adf-7bec0fe0b8b9",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a0d30309-65f4-453a-8281-b35faccfda13",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                        "guid": "d61fd658-ae56-435d-a2a9-27b0a4281408",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    }
                ],
                "view_fields": [],
                "relation_table_slug": "setting.timezones",
                "columns": [],
                "quick_filters": [],
                "default_values": [],
                "title": "test en",
                "dynamic_tables": []
            }

            if(type === "Many2Dynamic") payload.relation_field_slug = "something"
            const res = await relationStorage.create(payload)

            assert.equal(res.id, id)
            ids.push(id)
        }

    })
   
    it('Get List relation', async () => {
        const res = await relationStorage.getAll({
            project_id: "ecb08c73-3b52-42e9-970b-56be9b7c4e81",
            offset: 0,
            limit: 5,
            table_slug: "setting.languages"
        })
        
        assert.ok(res.relations?.length >= 5, "Response must have length in menus key")
    })

    it('Update relation', async () => {
        for(let id of ids) {
            const res = await relationStorage.update({
                project_id: "ecb08c73-3b52-42e9-970b-56be9b7c4e81",
                id: id,
                "table_from": "setting.timezones",
                "auto_filters": [],
                "action_relations": [],
                "attributes": {},
                "table_to": "setting.languages",
                "default_limit": "Unit test default limit after update",
                "multiple_insert": false,
                "filtersList": [
                    {
                    "attributes": {
                        "creatable": false,
                        "defaultValue": "",
                        "disabled": false,
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "6942f498-4097-44f0-837a-8a263420c7b2",
                        "guid": "06d51fc0-6084-4e4e-bf95-b99a0995c8d4",
                        "label": "name",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "placeholder": "",
                        "showTooltip": false,
                        "show_label": true
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "6942f498-4097-44f0-837a-8a263420c7b2",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "name",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": true,
                    "slug": "name",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "auto_filters": [],
                        "autofill": [],
                        "cascading_tree_field_slug": "",
                        "cascading_tree_table_slug": "",
                        "cascadings": [],
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                        "guid": "d2c0eac9-918f-4c7e-a3f6-dbea775a36b9",
                        "label": "FROM category TO connections",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "function_path": "",
                        "is_user_id_default": false,
                        "object_id_from_jwt": false,
                        "view_fields": []
                    },
                    "id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                    "label": "label",
                    "relation_id": "027cbe50-0f9a-4b2b-9433-69025dd198e1",
                    "required": false,
                    "slug": "connections_id",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "table_slug": "connections",
                    "type": "LOOKUP",
                    "view_fields": []
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                        "guid": "dd68e6a2-7404-4dbb-9652-e1a082277e22",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                        "guid": "05f30bc3-22cd-4b84-a6c8-4bc12a1db11c",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                        "guid": "eb2596f7-d43b-4fdd-9b17-0f654741dd5f",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                        "guid": "17d45ecf-a3eb-44fe-b8ea-660a6bd8fa3b",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                        "guid": "e2cc4d9b-1aec-4a41-93c3-4f5953a41df1",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                        "guid": "82e6cdb3-25c4-4ba8-ba6e-c1ff7cbf1e49",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                        "guid": "78ee1026-61de-40f5-9534-cdef3bc6848d",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                        "guid": "2a45c7cf-6729-42cb-8dbc-48af9bb3fa7c",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a0d30309-65f4-453a-8281-b35faccfda13",
                        "guid": "4a02e413-3b55-40a2-8adf-7bec0fe0b8b9",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a0d30309-65f4-453a-8281-b35faccfda13",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                        "guid": "d61fd658-ae56-435d-a2a9-27b0a4281408",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    }
                ],
                "columnsList": [
                    {
                    "attributes": {
                        "creatable": false,
                        "defaultValue": "",
                        "disabled": false,
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "6942f498-4097-44f0-837a-8a263420c7b2",
                        "guid": "06d51fc0-6084-4e4e-bf95-b99a0995c8d4",
                        "label": "name",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "placeholder": "",
                        "showTooltip": false,
                        "show_label": true
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "6942f498-4097-44f0-837a-8a263420c7b2",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "name",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": true,
                    "slug": "name",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "auto_filters": [],
                        "autofill": [],
                        "cascading_tree_field_slug": "",
                        "cascading_tree_table_slug": "",
                        "cascadings": [],
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                        "guid": "d2c0eac9-918f-4c7e-a3f6-dbea775a36b9",
                        "label": "FROM category TO connections",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "function_path": "",
                        "is_user_id_default": false,
                        "object_id_from_jwt": false,
                        "view_fields": []
                    },
                    "id": "7fe211bd-1ad5-4289-8eab-e5ace60ae251",
                    "label": "label",
                    "relation_id": "027cbe50-0f9a-4b2b-9433-69025dd198e1",
                    "required": false,
                    "slug": "connections_id",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "table_slug": "connections",
                    "type": "LOOKUP",
                    "view_fields": []
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                        "guid": "dd68e6a2-7404-4dbb-9652-e1a082277e22",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": false,
                    "hide_multilanguage": false,
                    "id": "ba8b67a6-64d6-4dbb-82c6-cd29f1b8f397",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                        "guid": "05f30bc3-22cd-4b84-a6c8-4bc12a1db11c",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "b2bb0af5-7fcc-412c-8385-dbca804a93be",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                        "guid": "eb2596f7-d43b-4fdd-9b17-0f654741dd5f",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "fd34fd95-0749-48d5-bb70-56195ce08916",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                        "guid": "17d45ecf-a3eb-44fe-b8ea-660a6bd8fa3b",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "63bb5962-9c86-494b-a488-6ce46ddd2977",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "new_ar_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                        "guid": "e2cc4d9b-1aec-4a41-93c3-4f5953a41df1",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "875528cc-9bce-4fd0-92a4-f60416c4a232",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                        "guid": "82e6cdb3-25c4-4ba8-ba6e-c1ff7cbf1e49",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a157ffe3-a967-4c3e-8030-25cfbeefb46c",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                        "guid": "78ee1026-61de-40f5-9534-cdef3bc6848d",
                        "label": "new",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "e0f82183-2568-46d5-9a1d-2332da8df07a",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "new",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "test_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "MULTI_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                        "guid": "2a45c7cf-6729-42cb-8dbc-48af9bb3fa7c",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "ae3225fa-837f-41df-b0e6-a93af1728db3",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "relation_id": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ar",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "a0d30309-65f4-453a-8281-b35faccfda13",
                        "guid": "4a02e413-3b55-40a2-8adf-7bec0fe0b8b9",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "a0d30309-65f4-453a-8281-b35faccfda13",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_la",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    },
                    {
                    "attributes": {
                        "defaultValue": "",
                        "field_permission": {
                        "edit_permission": true,
                        "field_id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                        "guid": "d61fd658-ae56-435d-a2a9-27b0a4281408",
                        "label": "The Arch",
                        "role_id": "3306fd21-ee1a-4c68-8843-6d0699b6f9ce",
                        "table_slug": "category",
                        "view_permission": true
                        },
                        "icon": "",
                        "showTooltip": false,
                        "show_label": false
                    },
                    "autofill_field": "",
                    "autofill_table": "",
                    "automatic": false,
                    "commit_id": "",
                    "default": "",
                    "enable_multilanguage": true,
                    "hide_multilanguage": false,
                    "id": "8bbeff74-aaf2-451c-ba3e-0e09380415a4",
                    "index": "string",
                    "is_system": false,
                    "is_visible": false,
                    "label": "The Arch",
                    "relation_field": "",
                    "required": false,
                    "show_label": false,
                    "slug": "arch_ms",
                    "table_id": "87be0812-6b52-435d-951f-6d49d3134d1e",
                    "type": "SINGLE_LINE",
                    "unique": false
                    }
                ],
                "view_fields": ["something"],
                "relation_table_slug": "setting.timezones",
                "columns": [],
                "quick_filters": [],
                "default_values": [],
                "title": "test en",
                "dynamic_tables": []
            })
        
            assert.ok(res.view_fields.length > 0, "View fields length must be equal to 1")
        }
    })

    it('Delete relation', async () => {

        for(let id of ids) {
            const res = await relationStorage.delete({
                project_id: "ecb08c73-3b52-42e9-970b-56be9b7c4e81",
                id: id
            })
    
            assert.equal(res.id, id)
        }
    })

})

