async function createTable() {
    let tables = [{
        "label": "Разрешение для связь",
        "slug": "view_relation_permission",
        "description": "Разрешение для связь которые в страница сведений",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "door-closed.svg",
        "subtitle_field_slug": "",
        "id": "074fcb3b-038d-483d-b390-ca69490fc4c3",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Связь",
        "slug": "connections",
        "description": "connections",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "brand_connectdevelop.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "0ade55f8-c84d-42b7-867f-6418e1314e28",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Роли",
        "slug": "role",
        "description": "role",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "brand_critical-role.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "1ab7fadc-1f2b-4934-879d-4e99772526ad",
        "created_at": new Date(),
        "updated_at": new Date(),
        "updated_at": {
            "$date": "2022-12-23T06:57:02.348Z"
        },
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Пользователи",
        "slug": "user",
        "description": "user",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "address-card.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "2546e042-af2f-4cef-be7c-834e6bde951c",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Разрешение",
        "slug": "record_permission",
        "description": "record permission",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "record-vinyl.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "25698624-5491-4c39-99ec-aed2eaf07b97",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Проект",
        "slug": "project",
        "description": "project",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "diagram-project.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "373e9aae-315b-456f-8ec3-0851cad46fbf",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Автоматический фильтр",
        "slug": "automatic_filter",
        "description": "Автоматический фильтр для матрица",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "filter.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "4c1f5c95-1528-4462-8d8c-cd377c23f7f7",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Клиент платформа",
        "slug": "client_platform",
        "description": "client platform",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "brand_bimobject.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "53edfff0-2a31-4c73-b230-06a134afa50b",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Разрешение на действие",
        "slug": "action_permission",
        "description": "Разрешение на действие",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "eye-dropper.svg",
        "subtitle_field_slug": "",
        "id": "5af2bfb2-6880-42ad-80c8-690e24a2523e",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Логин таблица",
        "slug": "test_login",
        "description": "Test Login",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "blog.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "5db33db7-4524-4414-b65a-b6b8e5bba345",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Разрешение поля",
        "slug": "field_permission",
        "description": "Разрешение поля",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "clapperboard.svg",
        "subtitle_field_slug": "",
        "id": "961a3201-65a4-452a-a8e1-7c7ba137789c",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    }, {
        "label": "Тип клиентов",
        "slug": "client_type",
        "description": "client type",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "angles-right.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "ed3bf0d9-40a3-4b79-beb4-52506aa0b5ea",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
    },{
        "label": "Шаблон",
        "slug": "template",
        "description": "Шаблоны",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "arrow-right-to-bracket.svg",
        "subtitle_field_slug": "",
        "id": "08972256-30fb-4d75-b8cf-940d8c4fc8ac",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
      },{
        "label": "Врачи",
        "slug": "doctors",
        "description": "Специалисты",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "stethoscope.svg",
        "subtitle_field_slug": "name",
        "with_increment_id": true,
        "digit_number": 3,
        "id": "6b99e876-b4d8-440c-b2e2-a961530690f8",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "soft_delete": false,
      },{
        "label": "Файл",
        "slug": "file",
        "description": "Файлы",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "file-arrow-down.svg",
        "subtitle_field_slug": "",
        "id": "b1896ed7-ba00-46ae-ae53-b424d2233589",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0
      },{
        "label": "Разрешение на приложении",
        "slug": "app_permission",
        "description": "Разрешение на приложении",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "file-arrow-down.svg",
        "subtitle_field_slug": "",
        "id": "41491588-53f1-4457-ba46-93019363ab88",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
      }]

    return tables;
}

module.exports = createTable