async function createTable() {
    let tables = [{
        "label": "Разрешение для связь",
        "slug": "view_relation_permission",
        "description": "Разрешение для связь которые в страница сведений",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "door-closed.svg",
        "subtitle_field_slug": "",
        "id": "074fcb3b-038d-483d-b390-ca69490fc4c3",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Связь",
        "slug": "connections",
        "description": "connections",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "brand_connectdevelop.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "0ade55f8-c84d-42b7-867f-6418e1314e28",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Роли",
        "slug": "role",
        "description": "role",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "brand_critical-role.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "1ab7fadc-1f2b-4934-879d-4e99772526ad",
        "created_at": new Date(),
        "updated_at": new Date(),
        "updated_at": {
            "$date": "2022-12-23T06:57:02.348Z"
        },
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Пользователи",
        "slug": "user",
        "description": "user",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "address-card.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "2546e042-af2f-4cef-be7c-834e6bde951c",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0
    },
    {
        "label": "Языки",
        "slug": "setting.languages",
        "description": "Языки",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "address-card.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "d267203c-1c23-4663-a721-7a845d4b98ad",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "is_system": true
    },
    {
        "label": "Часовые пояса",
        "slug": "setting.timezones",
        "description": "Часовые пояса",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "address-card.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "bba3dddc-5f20-449c-8ec8-37bef283c766",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "is_system": true
    },
    {
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Разрешение",
        "slug": "record_permission",
        "description": "record permission",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "record-vinyl.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "25698624-5491-4c39-99ec-aed2eaf07b97",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Проект",
        "slug": "project",
        "description": "project",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "diagram-project.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "373e9aae-315b-456f-8ec3-0851cad46fbf",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Автоматический фильтр",
        "slug": "automatic_filter",
        "description": "Автоматический фильтр для матрица",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "filter.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "4c1f5c95-1528-4462-8d8c-cd377c23f7f7",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Клиент платформа",
        "slug": "client_platform",
        "description": "client platform",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "brand_bimobject.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "53edfff0-2a31-4c73-b230-06a134afa50b",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Разрешение на действие",
        "slug": "action_permission",
        "description": "Разрешение на действие",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "eye-dropper.svg",
        "subtitle_field_slug": "",
        "id": "5af2bfb2-6880-42ad-80c8-690e24a2523e",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Логин таблица",
        "slug": "test_login",
        "description": "Test Login",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "blog.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "5db33db7-4524-4414-b65a-b6b8e5bba345",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Разрешение поля",
        "slug": "field_permission",
        "description": "Разрешение поля",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "clapperboard.svg",
        "subtitle_field_slug": "",
        "id": "961a3201-65a4-452a-a8e1-7c7ba137789c",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    }, {
        "label": "Тип клиентов",
        "slug": "client_type",
        "description": "client type",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "angles-right.svg",
        "subtitle_field_slug": "",
        "with_increment_id": false,
        "digit_number": 0,
        "id": "ed3bf0d9-40a3-4b79-beb4-52506aa0b5ea",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
    },{
        "label": "Шаблон",
        "slug": "template",
        "description": "Шаблоны",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "arrow-right-to-bracket.svg",
        "subtitle_field_slug": "",
        "id": "08972256-30fb-4d75-b8cf-940d8c4fc8ac",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
      },{
        "label": "Врачи",
        "slug": "doctors",
        "description": "Специалисты",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "stethoscope.svg",
        "subtitle_field_slug": "name",
        "with_increment_id": true,
        "digit_number": 3,
        "id": "6b99e876-b4d8-440c-b2e2-a961530690f8",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "soft_delete": false,
        "is_system": true,
      },{
        "label": "Файл",
        "slug": "file",
        "description": "Файлы",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "file-arrow-down.svg",
        "subtitle_field_slug": "",
        "id": "b1896ed7-ba00-46ae-ae53-b424d2233589",
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0
    }, {
        "id": "c2f225b6-b6d9-4201-aa25-e648a4c1ff29",
        "label": "Custom Error",
        "slug": "object_builder.custom_error",
        "description": "Custom Error",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "is_system": true,
        "icon": "bear-toy.svg",
        "subtitle_field_slug": "",
        "folder_id": "96ed7568-e086-48db-92b5-658450cbd4a8",
        "is_cached": false,
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "commit_guid": "277404a5-83ac-4a5c-8f4b-c38d10b1796b"
    }, {
        "id": "eca81c06-c4fc-4242-8dc9-ecca575e1762",
        "slug": "user_login_table",
        "label": "User Login Table",
        "description": "User Login Table",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "chalkboard-user.svg",
        "subtitle_field_slug": "",
        "folder_id": "",
        "is_cached": false,
        "is_system": false,
        "soft_delete": false,
        "created_at": new Date(),
        "updated_at": new Date(),
        "is_system": true,
        "__v": 0,
        "commit_guid": "58e790aa-06a2-4a11-ae4f-0ff7cf2f8b0b"
    },{
        "label": "Разрешение для меню",
        "slug": "menu_permission",
        "description": "Разрешение для связь которые в страница сведений",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "door-closed.svg",
        "subtitle_field_slug": "",
        "id": "08a391b2-1c78-4f3e-b84a-9d745e7d528f",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "is_system": true
    },
    {
        "label": "Разрешение для настройки  ",
        "slug": "global_permission",
        "description": "Разрешение для настройки",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "door-closed.svg",
        "subtitle_field_slug": "",
        "id": "1b066143-9aad-4b28-bd34-0032709e463b",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "is_system": true
    },
    {
        "label": "Разрешение для вид",
        "slug": "view_permission",
        "description": "Разрешение для вид",
        "deleted_at": new Date('1970-01-01T18:00:00.000+00:00'),
        "show_in_menu": true,
        "is_changed": false,
        "icon": "door-closed.svg",
        "subtitle_field_slug": "",
        "id": "65a7936b-f3db-4401-afef-8eee77b68da3",
        "created_at": new Date(),
        "updated_at": new Date(),
        "__v": 0,
        "is_system": true
    }]

    return tables;
}

module.exports = createTable